[package]
name = "amnesia_sigmod_demo"
version = "0.1.0"
authors = ["Sebastian <ssc@apache.org>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ws = "0.9"
timely = "0.10.0"
differential-dataflow = "0.10.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"